#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;


Dotenv\Dotenv::createImmutable(__DIR__)->load();

$application = new Application(config('app.name'));

\Core\Bootstrapers\ConfigureMigrations::initialize($application);

$commands = config('console.commands');

array_walk($commands, fn($command) => $application->add(new $command()));

array_map(function ($classCommand) use (&$application) {
    $class = config('console.path') . '/' . $classCommand;

    if (is_file($class) && pathinfo($class, PATHINFO_EXTENSION) == 'php') {
        $qualifiedName = (str_replace(".php", "", config('console.default_namespace') . '\\' . $classCommand));

        $reflection = new ReflectionClass($qualifiedName);

        $application->add($reflection->newInstance());
    }

}, scandir(config('console.path')));

$application->run();